#!/bin/bash
set -x
REDSOCKS=$(id -u redsocks)
SQUID=$(id -u proxy)

function stop () {
  echo "Disabling IPtables forwarding"
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D OUTPUT -j TRANSPARENTPROXY
  iptables -t nat -D OUTPUT -j TRANSPARENTPROXY
  iptables -t nat -D OUTPUT -m owner --uid-owner ${REDSOCKS} -j RETURN
  iptables -t nat -D OUTPUT -m owner --uid-owner ${REDSOCKS} -j RETURN
  iptables -t nat -D OUTPUT -m owner --uid-owner ${SQUID} -j RETURN
  iptables -t nat -D OUTPUT -m owner --uid-owner ${SQUID} -j RETURN

  iptables -t nat -F TRANSPARENTPROXY
  iptables -t nat -X TRANSPARENTPROXY

  kill ${RED_PID} || true
  kill ${SQUID_PID} || true

  exit 0
}

function start () {
  echo "Enabling IPTables forwarding"
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D OUTPUT -j TRANSPARENTPROXY
  iptables -t nat -D OUTPUT -j TRANSPARENTPROXY
  iptables -t nat -F TRANSPARENTPROXY
  iptables -t nat -X TRANSPARENTPROXY
  iptables -t nat -N TRANSPARENTPROXY

  iptables -t nat -A TRANSPARENTPROXY -p tcp --dport 43 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -p udp --dport 43 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 10.0.0.0/8 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 127.0.0.0/8 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 169.254.0.0/16 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 172.16.0.0/12 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 192.168.0.0/16 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 224.0.0.0/4 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -d 240.0.0.0/4 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -p tcp -d ${PROXY_HOST:-127.0.0.1} -dport ${PROXY_PORT:-3128} -j RETURN

  iptables -t nat -A TRANSPARENTPROXY -p tcp --dport 80 -j REDIRECT --to 12345
  iptables -t nat -A TRANSPARENTPROXY -p tcp --dport 8080 -j REDIRECT --to 12345
  iptables -t nat -A TRANSPARENTPROXY -p tcp -j REDIRECT --to 12346

  iptables -t nat -A PREROUTING -j TRANSPARENTPROXY

  if [[ "${REDIRECT:-docker}" = "all" ]]; then
    echo "REDIRECT local traffic to proxy"
    iptables -t nat -A OUTPUT -m owner --uid-owner ${REDSOCKS} -j RETURN
    iptables -t nat -A OUTPUT -m owner --uid-owner ${SQUID} -j RETURN
    iptables -t nat -A OUTPUT -j TRANSPARENTPROXY
  fi
}

startSquid () {
  if [[ ! -f /run/squid ]]; then
    chown -R proxy:proxy /var/cache/squid3
    echo "maximum_object_size ${MAXIMUM_CACHE_OBJECT:-1024} MB" >> /etc/squid3/squid.conf
    echo "cache_dir ufs /var/cache/squid3 ${DISK_CACHE_SIZE:-5000} 16 256" >> /etc/squid3/squid.conf
    echo "cache_peer ${PROXY_HOST:-55.1.35.230} parent ${PROXY_PORT:-8080} 0 no-query no-digest" >> /etc/squid3/squid.conf
    echo "never_direct allow all" >> /etc/squid3/squid.conf
    squid3 -z
    touch /run/squid
  fi
}

trap 'stop' SIGTERM SIGINT
start
/usr/sbin/redsocks -c /etc/redsocks.conf &
RED_PID=$!
startSquid
squid3 -N &
SQUID_PID=$!
while true; do sleep 5; done
