#!/bin/bash

set -x

function stop () {
  echo "Disabling IPtables forwarding"
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -F TRANSPARENTPROXY
  iptables -t nat -X TRANSPARENTPROXY
  exit 0
}

function start () {
  echo "Enabling IPTables forwarding"
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -D PREROUTING -j TRANSPARENTPROXY
  iptables -t nat -F TRANSPARENTPROXY
  iptables -t nat -X TRANSPARENTPROXY
  iptables -t nat -N TRANSPARENTPROXY

  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 10.0.0.0/8 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 127.0.0.0/8 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 169.254.0.0/16 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 172.16.0.0/12 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 192.168.0.0/16 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 224.0.0.0/4 -j RETURN
  iptables -t nat -A TRANSPARENTPROXY -i docker0 -d 240.0.0.0/4 -j RETURN

  iptables -t nat -A TRANSPARENTPROXY -p tcp --dport 80 -i docker0 -j REDIRECT --to 12345
  iptables -t nat -A TRANSPARENTPROXY -p tcp --dport 8080 -i docker0 -j REDIRECT --to 12345
  iptables -t nat -A TRANSPARENTPROXY -p tcp -i docker0 -j REDIRECT --to 12346

  iptables -t nat -I PREROUTING 1 -j TRANSPARENTPROXY
}

trap 'stop' SIGTERM SIGINT
start
while true; do sleep 5; done
